version: '3'

services:
  redis-master:
    image: redis:5.0.6-alpine
    container_name: redis-master
  redis-slave1:
    image: redis:5.0.6-alpine
    container_name: redis-slave1
    depends_on:
      - redis-master
    command: redis-server --slaveof redis-master 6379
  redis-slave2:
    image: redis:5.0.6-alpine
    container_name: redis-slave2
    depends_on:
      - redis-master
    command: redis-server --slaveof redis-master 6379
  phpunit-full:
    image: phpunit
    build: .
    volumes:
      - .:/var/www/html
    depends_on:
      - redis-master
      - redis-slave1
      - redis-slave2
    command: ./vendor/bin/phpunit --testsuite Medium --coverage-text
  phpunit:
    image: phpunit
    build: .
    volumes:
      - .:/var/www/html
    command: ./vendor/bin/phpunit --testsuite Small --coverage-text

